### ISSUE TITLE
Embed video doesn't show 'Video is processing, check back later' text

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#178]
Maybe one way to work around this is to hide the embed text until this is available

**Comment by pdpinch** [comment]
@mbertrand @gsidebo this was fixed by PR #242 right?

**Comment by mbertrand** [comment]
Still an issue, the text displays on the main video page but not the embed URL.
